### ISSUE TITLE
获取proto长时间会断开

### ISSUE THREAD

**Issue by dfaofeng** [SeeFlowerX/frida-protobuf#2]
bilibili版本是6.19.0```
[+]   944 com.bilibili.infoc.protobuf.f
[+]   945 com.bilibili.infoc.protobuf.g
[+]   946 com.bilibili.infoc.protobuf.h
[+]   947 com.bilibili.lib.deviceconfig.a
Traceback (most recent call last):
被动断开rpc -> process-terminated
  File "C:\Users\daofeng\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
args -> (Crash(pid=8813, process_name="Thread-32", summary="Trace/BPT trap", report=<860 bytes>, parameters={}),)
    return _run_code(code, main_globals, None,
  File "C:\Users\daofeng\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "F:\code\frida\frida-protobuf\frida_protobuf\main.py", line 114, in <module>
    main()
  File "F:\code\frida\frida-protobuf\frida_protobuf\main.py", line 107, in main
    rpc.dump(args.use_default_any, args.keywords_expected, args.keywords_unexpected)
  File "C:\Users\daofeng\AppData\Local\Programs\Python\Python39\lib\site-packages\frida\core.py", line 404, in method
    return script._rpc_request('call', js_name, args, **kwargs)
  File "C:\Users\daofeng\AppData\Local\Programs\Python\Python39\lib\site-packages\frida\core.py", line 26, in wrapper
    return f(*args, **kwargs)
  File "C:\Users\daofeng\AppData\Local\Programs\Python\Python39\lib\site-packages\frida\core.py", line 336, in _rpc_request
    raise result[2]
frida.InvalidOperationError: script is destroyed
```

**Comment by SeeFlowerX** [comment]
1. 建议使用linux
2. 把[这个位置](https://github.com/SeeFlowerX/frida-protobuf/blob/ac231582a29f92988886a5f9e89df472a980f7bb/agent/src/index.ts#L99)的注释取消掉，看看是在那个地方卡住了，跳过卡住的这个类，再重新跑

**Comment by SeeFlowerX** [comment]
**合理使用--keywords-expected可以避免APP崩溃或卡死**

卡住的主要原因是`getCls`这里发生的，对于某些类确实会卡住，原因暂不明了

所以最佳解决方案是跳过用`--unkeywords-expected`

以及用`--keywords-expected`直接遍历目标

如果仍然有疑问请重新打开此issue
