### ISSUE TITLE
The process terminated in the middle

### ISSUE THREAD

**Issue by chuxuanhy** [SeeFlowerX/frida-protobuf#6]
Hello,

I got the source running, but it got terminated in the middle. I tried reading the source to figure it out. How can I fix it? Please give me some hints.

Regards.

2024-07-30 17:08:30,555 main log.py 29 : INFO  创建 -> frida_protobuf\logs\main-2024-07-30_170830.log
2024-07-30 17:08:30,557 main main.py 84 : INFO  start attach tv.danmaku.bili
2024-07-30 17:08:32,099 main main.py 99 : INFO  attach tv.danmaku.bili success, inject script now
E:\Dropbox\SourceCode\frida-protobuf\frida_protobuf\main.py:109: DeprecationWarning: Script.exports will become asynchronous in the future, use the explicit Script.exports_sync instead
  rpc = script.exports
[-] start enumerate /data/app/~~8KlLwDvHPZboOa9oXE0e0Q==/tv.danmaku.bili-OPznS_tNcZKRbNvOj5Vl1Q==/base.apk dexfile_name include /system => false
[+]     1 com.bapis.bilibili.account.fission.v1.AnimateIcon
[+]     2 com.bapis.bilibili.account.fission.v1.EntranceReply
[+]     3 com.bapis.bilibili.account.fission.v1.EntranceReq
[+]     4 com.bapis.bilibili.account.fission.v1.WindowReply
[+]     5 com.bapis.bilibili.account.fission.v1.WindowReq
[+]     6 com.bapis.bilibili.ad.v1.AdAutoPlayVideoDto
[+]     7 com.bapis.bilibili.ad.v1.AdBusinessMarkDto
[+]     8 com.bapis.bilibili.ad.v1.AdButtonDto
[+]     9 com.bapis.bilibili.ad.v1.AdCardDto
[+]    10 com.bapis.bilibili.ad.v1.AdContentExtraDto
[+]    11 com.bapis.bilibili.ad.v1.AdCoverDto
[+]    12 com.bapis.bilibili.ad.v1.AdDto
[+]    13 com.bapis.bilibili.ad.v1.AdFeedbackPanelDto
[+]    14 com.bapis.bilibili.ad.v1.AdFeedbackPanelModuleDto
[+]    15 com.bapis.bilibili.ad.v1.AdGoodDto
[+]    16 com.bapis.bilibili.ad.v1.AdOgvEpDto
[+]    17 com.bapis.bilibili.ad.v1.AdSecondFeedbackPanelDto
[+]    18 com.bapis.bilibili.ad.v1.AdShareInfoDto
[+]    19 com.bapis.bilibili.ad.v1.AdsControlDto
[+]    20 com.bapis.bilibili.ad.v1.AdverDto
[+]    21 com.bapis.bilibili.ad.v1.AppPackageDto
[+]    22 com.bapis.bilibili.ad.v1.CreativeDto
[+]    23 com.bapis.bilibili.ad.v1.QualityInfo
[+]    24 com.bapis.bilibili.ad.v1.SourceContentDto
[+]    25 com.bapis.bilibili.api.player.v1.HeartbeatReply
[+]    26 com.bapis.bilibili.api.player.v1.HeartbeatReq
[+]    27 com.bapis.bilibili.api.probe.v1.CodeReply
[+]    28 com.bapis.bilibili.api.probe.v1.CodeReq
[+]    29 com.bapis.bilibili.api.probe.v1.ProbeReply
[+]    30 com.bapis.bilibili.api.probe.v1.ProbeReq
[+]    31 com.bapis.bilibili.api.probe.v1.ProbeStreamReply
[+]    32 com.bapis.bilibili.api.probe.v1.ProbeStreamReq
[+]    33 com.bapis.bilibili.api.probe.v1.ProbeSubReply
[+]    34 com.bapis.bilibili.api.probe.v1.ProbeSubReq
[+]    35 com.bapis.bilibili.app.archive.middleware.v1.PlayerArgs
[+]    36 com.bapis.bilibili.app.archive.v1.Arc
[+]    37 com.bapis.bilibili.app.archive.v1.Author
[+]    38 com.bapis.bilibili.app.archive.v1.Dimension
[+]    39 com.bapis.bilibili.app.archive.v1.Page
[+]    40 com.bapis.bilibili.app.archive.v1.Rights
[+]    41 com.bapis.bilibili.app.archive.v1.StaffInfo
[+]    42 com.bapis.bilibili.app.archive.v1.Stat
[+]    43 com.bapis.bilibili.app.card.v1.AdInfo
[+]    44 com.bapis.bilibili.app.card.v1.Args
[+]    45 com.bapis.bilibili.app.card.v1.Avatar
[+]    46 com.bapis.bilibili.app.card.v1.Base
[+]    47 com.bapis.bilibili.app.card.v1.Bubble
[+]    48 com.bapis.bilibili.app.card.v1.Button
[+]    49 com.bapis.bilibili.app.card.v1.Card
[+]    50 com.bapis.bilibili.app.card.v1.CreativeContent
[+]    51 com.bapis.bilibili.app.card.v1.DislikeReason
[+]    52 com.bapis.bilibili.app.card.v1.DoubleCards
[+]    53 com.bapis.bilibili.app.card.v1.DynamicHot
[+]    54 com.bapis.bilibili.app.card.v1.EntranceItem
[+]    55 com.bapis.bilibili.app.card.v1.HotTopic
[+]    56 com.bapis.bilibili.app.card.v1.HotTopicItem
[+]    57 com.bapis.bilibili.app.card.v1.HotwordEntrance
[+]    58 com.bapis.bilibili.app.card.v1.LargeCoverV1
[+]    59 com.bapis.bilibili.app.card.v1.LargeCoverV2
[+]    60 com.bapis.bilibili.app.card.v1.LargeCoverV3
[+]    61 com.bapis.bilibili.app.card.v1.LargeCoverV4
[+]    62 com.bapis.bilibili.app.card.v1.LikeButton
[+]    63 com.bapis.bilibili.app.card.v1.Mask
[+]    64 com.bapis.bilibili.app.card.v1.MiddleCoverV2
[+]    65 com.bapis.bilibili.app.card.v1.MiddleCoverV3
[+]    66 com.bapis.bilibili.app.card.v1.MultiItem
[+]    67 com.bapis.bilibili.app.card.v1.OnePicV2
[+]    68 com.bapis.bilibili.app.card.v1.OnePicV3
[+]    69 com.bapis.bilibili.app.card.v1.PlayerArgs
[+]    70 com.bapis.bilibili.app.card.v1.PopularTopEntrance
[+]    71 com.bapis.bilibili.app.card.v1.RcmdOneItem
[+]    72 com.bapis.bilibili.app.card.v1.ReasonStyle
[+]    73 com.bapis.bilibili.app.card.v1.Relation
[+]    74 com.bapis.bilibili.app.card.v1.SharePlane
[+]    75 com.bapis.bilibili.app.card.v1.SmallChannelSpecial
[+]    76 com.bapis.bilibili.app.card.v1.SmallCoverConvergeV2
[+]    77 com.bapis.bilibili.app.card.v1.SmallCoverRcmdItem
[+]    78 com.bapis.bilibili.app.card.v1.SmallCoverV2
[+]    79 com.bapis.bilibili.app.card.v1.SmallCoverV3
[+]    80 com.bapis.bilibili.app.card.v1.SmallCoverV4
[+]    81 com.bapis.bilibili.app.card.v1.SmallCoverV5
[+]    82 com.bapis.bilibili.app.card.v1.SmallCoverV7
[+]    83 com.bapis.bilibili.app.card.v1.SmallCoverV9
[+]    84 com.bapis.bilibili.app.card.v1.ThreeItemAllV2
[+]    85 com.bapis.bilibili.app.card.v1.ThreeItemV1
[+]    86 com.bapis.bilibili.app.card.v1.ThreeItemV1Item
[+]    87 com.bapis.bilibili.app.card.v1.ThreeItemV2
[+]    88 com.bapis.bilibili.app.card.v1.ThreeItemV2Item
[+]    89 com.bapis.bilibili.app.card.v1.ThreePicV2
[+]    90 com.bapis.bilibili.app.card.v1.ThreePicV3
[+]    91 com.bapis.bilibili.app.card.v1.ThreePoint
[+]    92 com.bapis.bilibili.app.card.v1.ThreePointV2
[+]    93 com.bapis.bilibili.app.card.v1.ThreePointV3
[+]    94 com.bapis.bilibili.app.card.v1.ThreePointV4
[+]    95 com.bapis.bilibili.app.card.v1.TwoItemHV1Item
[+]    96 com.bapis.bilibili.app.card.v1.TwoItemV2
[+]    97 com.bapis.bilibili.app.card.v1.TwoItemV2Item
[+]    98 com.bapis.bilibili.app.card.v1.Up
[+]    99 com.bapis.bilibili.app.card.v1.WatchLater
[+]   100 com.bapis.bilibili.app.distribution.BoolValue
[+]   101 com.bapis.bilibili.app.distribution.BytesValue
[+]   102 com.bapis.bilibili.app.distribution.DoubleValue
[+]   103 com.bapis.bilibili.app.distribution.FloatValue
[+]   104 com.bapis.bilibili.app.distribution.GetUserPreferenceReply
[+]   105 com.bapis.bilibili.app.distribution.GetUserPreferenceReq
[+]   106 com.bapis.bilibili.app.distribution.Int32Value
[+]   107 com.bapis.bilibili.app.distribution.Int64Value
[+]   108 com.bapis.bilibili.app.distribution.SetUserPreferenceReply
[+]   109 com.bapis.bilibili.app.distribution.SetUserPreferenceReq
[+]   110 com.bapis.bilibili.app.distribution.StringValue
[+]   111 com.bapis.bilibili.app.distribution.UInt32Value
[+]   112 com.bapis.bilibili.app.distribution.UInt64Value
[+]   113 com.bapis.bilibili.app.distribution.UserPreferenceReply
[+]   114 com.bapis.bilibili.app.distribution.UserPreferenceReq
[+]   115 com.bapis.bilibili.app.distribution.defaultValue
[+]   116 com.bapis.bilibili.app.distribution.setting.download.DownloadSettingsConfig
[+]   117 com.bapis.bilibili.app.distribution.setting.dynamic.DynamicAutoPlay
[+]   118 com.bapis.bilibili.app.distribution.setting.dynamic.DynamicDeviceConfig
[+]   119 com.bapis.bilibili.app.distribution.setting.experimental.Exp
[+]   120 com.bapis.bilibili.app.distribution.setting.experimental.ExperimentalConfig
[+]   121 com.bapis.bilibili.app.distribution.setting.night.NightSettingsConfig
[+]   122 com.bapis.bilibili.app.distribution.setting.other.OtherSettingsConfig
[+]   123 com.bapis.bilibili.app.distribution.setting.pegasus.FeedModeValue
[+]   124 com.bapis.bilibili.app.distribution.setting.pegasus.PegasusAutoPlay
[+]   125 com.bapis.bilibili.app.distribution.setting.pegasus.PegasusColumnValue
[+]   126 com.bapis.bilibili.app.distribution.setting.pegasus.PegasusDeviceConfig
[+]   127 com.bapis.bilibili.app.distribution.setting.play.PlayConfig
[+]   128 com.bapis.bilibili.app.distribution.setting.privacy.PrivacySettingsConfig
[+]   129 com.bapis.bilibili.app.distribution.setting.search.SearchAutoPlay
[+]   130 com.bapis.bilibili.app.distribution.setting.search.SearchDeviceConfig
[+]   131 com.bapis.bilibili.app.dynamic.v1.AdInfo
[+]   132 com.bapis.bilibili.app.dynamic.v1.AddressComponent
[+]   133 com.bapis.bilibili.app.dynamic.v1.BgType
[+]   134 com.bapis.bilibili.app.dynamic.v1.CardCurrBatch
[+]   135 com.bapis.bilibili.app.dynamic.v1.CardCurrSeason
[+]   136 com.bapis.bilibili.app.dynamic.v1.CardPGC
[+]   137 com.bapis.bilibili.app.dynamic.v1.CardUGC
[+]   138 com.bapis.bilibili.app.dynamic.v1.CornerType
[+]   139 com.bapis.bilibili.app.dynamic.v1.DecoCardFan
[+]   140 com.bapis.bilibili.app.dynamic.v1.DecorateCard
[+]   141 com.bapis.bilibili.app.dynamic.v1.Description
[+]   142 com.bapis.bilibili.app.dynamic.v1.Dimension
[+]   143 com.bapis.bilibili.app.dynamic.v1.DynDetailsReply
[+]   144 com.bapis.bilibili.app.dynamic.v1.DynDetailsReq
[+]   145 com.bapis.bilibili.app.dynamic.v1.DynMixUpListSearchReply
[+]   146 com.bapis.bilibili.app.dynamic.v1.DynMixUpListSearchReq
[+]   147 com.bapis.bilibili.app.dynamic.v1.DynMixUpListViewMoreReply
[+]   148 com.bapis.bilibili.app.dynamic.v1.DynOurCityItem
[+]   149 com.bapis.bilibili.app.dynamic.v1.DynOurCityModule
[+]   150 com.bapis.bilibili.app.dynamic.v1.DynOurCityModuleAuthor
[+]   151 com.bapis.bilibili.app.dynamic.v1.DynOurCityModuleCover
[+]   152 com.bapis.bilibili.app.dynamic.v1.DynOurCityModuleDesc
[+]   153 com.bapis.bilibili.app.dynamic.v1.DynOurCityModuleExtend
[+]   154 com.bapis.bilibili.app.dynamic.v1.DynOurCityModuleExtendLBS
[+]   155 com.bapis.bilibili.app.dynamic.v1.DynOurCityReply
[+]   156 com.bapis.bilibili.app.dynamic.v1.DynOurCityReq
[+]   157 com.bapis.bilibili.app.dynamic.v1.DynOurCitySwitchReq
[+]   158 com.bapis.bilibili.app.dynamic.v1.DynRedItem
[+]   159 com.bapis.bilibili.app.dynamic.v1.DynRedReply
[+]   160 com.bapis.bilibili.app.dynamic.v1.DynRedReq
[+]   161 com.bapis.bilibili.app.dynamic.v1.DynRedStyle
[+]   162 com.bapis.bilibili.app.dynamic.v1.DynRedStyleUp
[+]   163 com.bapis.bilibili.app.dynamic.v1.DynTab
[+]   164 com.bapis.bilibili.app.dynamic.v1.DynTabReply
[+]   165 com.bapis.bilibili.app.dynamic.v1.DynTabReq
[+]   166 com.bapis.bilibili.app.dynamic.v1.DynUpdOffsetReq
[+]   167 com.bapis.bilibili.app.dynamic.v1.DynVideoPersonalReply
[+]   168 com.bapis.bilibili.app.dynamic.v1.DynVideoPersonalReq
[+]   169 com.bapis.bilibili.app.dynamic.v1.DynVideoReq
[+]   170 com.bapis.bilibili.app.dynamic.v1.DynVideoReqReply
[+]   171 com.bapis.bilibili.app.dynamic.v1.DynamicItem
[+]   172 com.bapis.bilibili.app.dynamic.v1.Exp
[+]   173 com.bapis.bilibili.app.dynamic.v1.ExpConf
[+]   174 com.bapis.bilibili.app.dynamic.v1.ExtInfoGame
[+]   175 com.bapis.bilibili.app.dynamic.v1.ExtInfoHot
[+]   176 com.bapis.bilibili.app.dynamic.v1.ExtInfoLBS
[+]   177 com.bapis.bilibili.app.dynamic.v1.ExtInfoTopic
[+]   178 com.bapis.bilibili.app.dynamic.v1.Extend
[+]   179 com.bapis.bilibili.app.dynamic.v1.FoldType
[+]   180 com.bapis.bilibili.app.dynamic.v1.FollowListItem
[+]   181 com.bapis.bilibili.app.dynamic.v1.GeoCoderReply
[+]   182 com.bapis.bilibili.app.dynamic.v1.GeoCoderReq
Traceback (most recent call last):
被动断开rpc -> process-terminated
  File "C:\Python\Python37\lib\runpy.py", line 193, in _run_module_as_main
args -> (None,)
    "__main__", mod_spec)
  File "C:\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "E:\Dropbox\SourceCode\frida-protobuf\frida_protobuf\main.py", line 117, in <module>
    main()
  File "E:\Dropbox\SourceCode\frida-protobuf\frida_protobuf\main.py", line 110, in main
    rpc.dump(args.use_default_any, args.keywords_expected, args.keywords_unexpected)
  File "C:\Python\Python37\lib\site-packages\frida\core.py", line 180, in method
    return script._rpc_request(request, data, **kwargs)
  File "C:\Python\Python37\lib\site-packages\frida\core.py", line 86, in wrapper
    return f(*args, **kwargs)
  File "C:\Python\Python37\lib\site-packages\frida\core.py", line 497, in _rpc_request
    raise result.error
frida.InvalidOperationError: script has been destroyed

**Comment by SeeFlowerX** [comment]
its anti frida

**Comment by 12qwertyuiop** [comment]
我也遇到同样的问题
